def my_function():
    x = 10  
    print(x)

my_function() 
print(x)  

"""
Note 1: Here x is defined inside my_function() so as soon as function scope ends the value of x get over . So in Line no 6 it will get error.
"""
